### ISSUE TITLE
Are you maintaining the project? 

### ISSUE THREAD

**Issue by ebisbe** [sjmeverett/cfn-types#1]
Hi, I found your project and it's a bit outdated. Are you still using it? I'd like to update the package or take over so we can publish new versions.

**Comment by sjmeverett** [comment]
Hey, thanks for getting in touch. I'm actually going to be contributing to this [this very similar project](https://github.com/awboost/cfntypes) going forward, which keeps itself up to date with AWS automatically. We're going to be working on various tooling there too.

**Comment by ebisbe** [comment]
Glad to hear that then! I made a fork but will test and use the other one.
